package main

import (
	"github.com/swagger-api2cart/mcp-server/config"
	"github.com/swagger-api2cart/mcp-server/models"
	tools_order "github.com/swagger-api2cart/mcp-server/tools/order"
	tools_category "github.com/swagger-api2cart/mcp-server/tools/category"
	tools_cart "github.com/swagger-api2cart/mcp-server/tools/cart"
	tools_product "github.com/swagger-api2cart/mcp-server/tools/product"
	tools_attribute "github.com/swagger-api2cart/mcp-server/tools/attribute"
	tools_account "github.com/swagger-api2cart/mcp-server/tools/account"
	tools_webhook "github.com/swagger-api2cart/mcp-server/tools/webhook"
	tools_basket "github.com/swagger-api2cart/mcp-server/tools/basket"
	tools_customer "github.com/swagger-api2cart/mcp-server/tools/customer"
	tools_bridge "github.com/swagger-api2cart/mcp-server/tools/bridge"
	tools_tax "github.com/swagger-api2cart/mcp-server/tools/tax"
	tools_subscriber "github.com/swagger-api2cart/mcp-server/tools/subscriber"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_order.CreateOrderfulfillmentstatuslistTool(cfg),
		tools_order.CreateOrderinfoTool(cfg),
		tools_category.CreateCategoryinfoTool(cfg),
		tools_cart.CreateCartdeleteTool(cfg),
		tools_product.CreateProductvariantdeleteTool(cfg),
		tools_category.CreateCategoryassignTool(cfg),
		tools_product.CreateProductfieldsTool(cfg),
		tools_order.CreateOrdercountTool(cfg),
		tools_order.CreateOrdertransactionlistTool(cfg),
		tools_attribute.CreateAttributeupdateTool(cfg),
		tools_order.CreateOrdershipmentinfoTool(cfg),
		tools_product.CreateProductvariantlistTool(cfg),
		tools_product.CreateProductvariantaddTool(cfg),
		tools_order.CreateOrderaddTool(cfg),
		tools_order.CreateOrdershipmentdeleteTool(cfg),
		tools_product.CreateProductvariantimageaddTool(cfg),
		tools_cart.CreateCartcatalogpricerulescountTool(cfg),
		tools_product.CreateProductcountTool(cfg),
		tools_account.CreateAccountcartlistTool(cfg),
		tools_webhook.CreateWebhookdeleteTool(cfg),
		tools_category.CreateCategorydeleteTool(cfg),
		tools_product.CreateProductbrandlistTool(cfg),
		tools_cart.CreateCartclearcacheTool(cfg),
		tools_cart.CreateCartmetadatasetTool(cfg),
		tools_attribute.CreateAttributeattributesetlistTool(cfg),
		tools_attribute.CreateAttributeunassignsetTool(cfg),
		tools_product.CreateProductimageaddTool(cfg),
		tools_basket.CreateBasketinfoTool(cfg),
		tools_product.CreateProductlistTool(cfg),
		tools_product.CreateProductvariantpriceaddTool(cfg),
		tools_attribute.CreateAttributegrouplistTool(cfg),
		tools_basket.CreateBasketliveshippingservicelistTool(cfg),
		tools_attribute.CreateAttributeinfoTool(cfg),
		tools_product.CreateProductcurrencylistTool(cfg),
		tools_order.CreateOrderpreestimateshippinglistTool(cfg),
		tools_product.CreateProductvariantpriceupdateTool(cfg),
		tools_product.CreateProductpriceaddTool(cfg),
		tools_cart.CreateCartcouponconditionaddTool(cfg),
		tools_order.CreateOrderfindTool(cfg),
		tools_attribute.CreateAttributetypelistTool(cfg),
		tools_product.CreateProductinfoTool(cfg),
		tools_cart.CreateCartmethodsTool(cfg),
		tools_webhook.CreateWebhookeventsTool(cfg),
		tools_customer.CreateCustomergroupaddTool(cfg),
		tools_product.CreateProductattributevaluesetTool(cfg),
		tools_product.CreateProductchilditemfindTool(cfg),
		tools_order.CreateOrderstatuslistTool(cfg),
		tools_webhook.CreateWebhookcountTool(cfg),
		tools_webhook.CreateWebhookcreateTool(cfg),
		tools_cart.CreateCartcoupondeleteTool(cfg),
		tools_cart.CreateCartmetadatalistTool(cfg),
		tools_cart.CreateCartcatalogpriceruleslistTool(cfg),
		tools_cart.CreateCartvalidateTool(cfg),
		tools_product.CreateProductoptionvalueupdateTool(cfg),
		tools_product.CreateProductpriceupdateTool(cfg),
		tools_cart.CreateCartcreateTool(cfg),
		tools_customer.CreateCustomerfindTool(cfg),
		tools_order.CreateOrderrefundaddTool(cfg),
		tools_product.CreateProductoptionaddTool(cfg),
		tools_attribute.CreateAttributeassigngroupTool(cfg),
		tools_product.CreateProductreviewlistTool(cfg),
		tools_product.CreateProductvariantimagedeleteTool(cfg),
		tools_attribute.CreateAttributelistTool(cfg),
		tools_attribute.CreateAttributeassignsetTool(cfg),
		tools_basket.CreateBasketliveshippingservicecreateTool(cfg),
		tools_cart.CreateCartgiftcardcountTool(cfg),
		tools_order.CreateOrderabandonedlistTool(cfg),
		tools_cart.CreateCartgiftcardaddTool(cfg),
		tools_customer.CreateCustomerattributelistTool(cfg),
		tools_customer.CreateCustomergrouplistTool(cfg),
		tools_product.CreateProductattributevalueunsetTool(cfg),
		tools_category.CreateCategoryimageaddTool(cfg),
		tools_product.CreateProductpricedeleteTool(cfg),
		tools_customer.CreateCustomerlistTool(cfg),
		tools_product.CreateProductoptionvalueassignTool(cfg),
		tools_cart.CreateCartdisconnectTool(cfg),
		tools_cart.CreateCartscriptdeleteTool(cfg),
		tools_product.CreateProductimageupdateTool(cfg),
		tools_account.CreateAccountfailedwebhooksTool(cfg),
		tools_order.CreateOrderupdateTool(cfg),
		tools_category.CreateCategorycountTool(cfg),
		tools_order.CreateOrdershipmentlistTool(cfg),
		tools_webhook.CreateWebhookupdateTool(cfg),
		tools_product.CreateProductcurrencyaddTool(cfg),
		tools_bridge.CreateBridgedeleteTool(cfg),
		tools_account.CreateAccountcartaddTool(cfg),
		tools_category.CreateCategoryaddTool(cfg),
		tools_product.CreateProductvariantcountTool(cfg),
		tools_attribute.CreateAttributeaddTool(cfg),
		tools_cart.CreateCartshippingzoneslistTool(cfg),
		tools_category.CreateCategoryfindTool(cfg),
		tools_product.CreateProductstoreassignTool(cfg),
		tools_tax.CreateTaxclassinfoTool(cfg),
		tools_product.CreateProductchilditemlistTool(cfg),
		tools_basket.CreateBasketitemaddTool(cfg),
		tools_cart.CreateCartconfigupdateTool(cfg),
		tools_product.CreateProductvariantpricedeleteTool(cfg),
		tools_cart.CreateCartcouponcountTool(cfg),
		tools_attribute.CreateAttributecountTool(cfg),
		tools_cart.CreateCartcouponlistTool(cfg),
		tools_order.CreateOrdershipmentupdateTool(cfg),
		tools_category.CreateCategoryunassignTool(cfg),
		tools_cart.CreateCartgiftcardlistTool(cfg),
		tools_product.CreateProductvariantinfoTool(cfg),
		tools_basket.CreateBasketliveshippingservicedeleteTool(cfg),
		tools_order.CreateOrderfinancialstatuslistTool(cfg),
		tools_cart.CreateCartinfoTool(cfg),
		tools_product.CreateProductchilditeminfoTool(cfg),
		tools_cart.CreateCartscriptlistTool(cfg),
		tools_product.CreateProductfindTool(cfg),
		tools_cart.CreateCartpluginlistTool(cfg),
		tools_product.CreateProductimagedeleteTool(cfg),
		tools_cart.CreateCartconfigTool(cfg),
		tools_product.CreateProductupdateTool(cfg),
		tools_product.CreateProducttaxaddTool(cfg),
		tools_customer.CreateCustomercountTool(cfg),
		tools_category.CreateCategoryupdateTool(cfg),
		tools_cart.CreateCartscriptaddTool(cfg),
		tools_webhook.CreateWebhooklistTool(cfg),
		tools_order.CreateOrdershipmentaddTool(cfg),
		tools_attribute.CreateAttributeunassigngroupTool(cfg),
		tools_product.CreateProductoptionlistTool(cfg),
		tools_cart.CreateCartlistTool(cfg),
		tools_product.CreateProductvariantupdateTool(cfg),
		tools_customer.CreateCustomeraddTool(cfg),
		tools_product.CreateProductaddTool(cfg),
		tools_product.CreateProductdeleteTool(cfg),
		tools_customer.CreateCustomerwishlistlistTool(cfg),
		tools_bridge.CreateBridgeupdateTool(cfg),
		tools_attribute.CreateAttributedeleteTool(cfg),
		tools_cart.CreateCartmetadataunsetTool(cfg),
		tools_product.CreateProductmanufactureraddTool(cfg),
		tools_order.CreateOrderlistTool(cfg),
		tools_account.CreateAccountsupportedplatformsTool(cfg),
		tools_product.CreateProductoptionassignTool(cfg),
		tools_category.CreateCategoryimagedeleteTool(cfg),
		tools_order.CreateOrdershipmenttrackingaddTool(cfg),
		tools_customer.CreateCustomerupdateTool(cfg),
		tools_product.CreateProductoptionvalueaddTool(cfg),
		tools_account.CreateAccountconfigupdateTool(cfg),
		tools_product.CreateProductattributelistTool(cfg),
		tools_subscriber.CreateSubscriberlistTool(cfg),
		tools_cart.CreateCartcouponaddTool(cfg),
		tools_cart.CreateCartbridgeTool(cfg),
		tools_category.CreateCategorylistTool(cfg),
		tools_customer.CreateCustomerinfoTool(cfg),
	}
}
